# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-10 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swiped',
            old_name='datetime',
            new_name='stime',
        ),
    ]
