# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-05 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=64, unique=True, verbose_name='手机')),
                ('nickname', models.CharField(default='匿名用户', max_length=64, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=6, verbose_name='性别')),
                ('birthday', models.DateField(default='1990-01-01', max_length=32, verbose_name='生日')),
                ('location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('郑州', '郑州'), ('西安', '西安'), ('成都', '成都'), ('沈阳', '沈阳')], max_length=256, verbose_name='常住地')),
                ('avatar', models.CharField(max_length=256, verbose_name='形象')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
